version: "2"
services:
  redis:
    image: redis:3.0-alpine
    ports:
      - "127.0.0.1:6379:6379"
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "127.0.0.1:5432:5432"
