version: 2
jobs:
  build:
    working_directory: ~/tictag
    docker:
      - image: johnswanson/docker-clojure:latest
    environment:
      LEIN_ROOT=nbd
      TIMBRE_LEVEL=':warn'
    steps:
      - checkout
      - restore_cache:
          key: deps-<< checksum "project.clj" >>
      - restore_cache:
          key: deps-<< checksum "package.json" >>
      - run: npm i
      - save_cache:
          paths:
            - ~/tictag/node_modules
          key: deps-<< checksum "project.clj" >>
      - run: node_modules/postcss-cli/bin/postcss resources/css/* -o resources/public/css/out.css
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: deps-<< checksum "project.clj" >>
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/tictag.jar
          destination: uberjar
      - add_ssh_keys
      - deploy:
          name: Deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then bin/deploy; fi
