version: 2
jobs:
  build:
    working_directory: ~/tictag
    docker:
      - image: clojure:lein-2.7.1
    environment:
      LEIN_ROOT=nbd
      TIMBRE_LEVEL=':warn'
    steps:
      - checkout
      - restore_cache:
          key: deps-<< checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: deps-<< checksum "project.clj" >>
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/tictag.jar
          destination: uberjar
      - add_ssh_keys
      - deploy:
          name: Deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then bin/deploy; fi
